In [1]:
import requests
import pprint

In [2]:
#1 The first step is to look for relevant table. In this case it is actually faster to paste the URL to chrome and do search function.
#URL is 'https://www150.statcan.gc.ca/t1/wds/rest/getAllCubesListLite'

#2. We found that the table we want is "Average satisfaction with life and with selected domains of life by age group and sex"
#3. What's important is the productId, which is be used for downloading the CSV.
#4. Product id is 13100106
#5. The next thing to do is to call the download method.
#https://www150.statcan.gc.ca/t1/wds/rest/getFullTableDownloadCSV/{product_id}/en

In [1]:
#Apply the GetFullTable Method

In [2]:
#get download path

In [3]:
#Capture the file name with regex
import re

In [4]:
# Create request to download...

In [80]:
#because the data is in zip format, use python to unzip it

   # Extract all the contents of zip file in current directory

In [1]:
# clean the data, get the columns we want
import pandas as pd
df_rawstatcan = pd.read_csv("../../01Resources/Data/raw_statcan.csv")

df_rawstatcan.head()

,ethnicity,topic,characteristics,AB,BC,MB,SK,NL,NS,NB,...,NL_Female,NS_Female,NB_Female,PE_Female,NU_Female,QC_Female,ON_Female,YU_Female,NW_Female,National_Female
0,Aboriginal,Ethnic origin population,North American Aboriginal origins,303815,302810,225230,177355,58550,74040,46585,...,30385,39115,23955,2640,15075,186985,271135,4325,10530,1103840
1,White,Ethnic origin population,Other North American origins,955040,922690,247670,230620,280640,410825,428865,...,143610,212855,219250,32130,860,2459605,1635340,4565,4020,5882835
2,White,Ethnic origin population,European origins,2580720,2857080,826210,759080,274460,621525,424850,...,140390,321760,218135,50920,3975,1526825,4172570,12465,8780,9995605
3,Black,Ethnic origin population,Caribbean origins,36120,25010,10805,3810,885,5220,2275,...,430,2640,1230,180,45,107690,248940,95,110,399345
4,Other Minority,Ethnic origin population,Latin; Central and South American origins,78405,69920,23115,6695,925,3055,2135,...,520,1525,1025,205,35,86065,169165,105,110,349430

In [2]:
#df.to_csv('Output/statcan_csv.csv')

In [3]:
#create database connection and load database
from sqlalchemy import create_engine
connection_string = "postgres:123@localhost:5432/Project2"
engine = create_engine(f'postgresql://{connection_string}')

In [18]:
engine.table_names()

['raw_incarceration', 'raw_statcan', 'table1', 'table2', 'table3', 'table4']

In [5]:
df_rawstatcan.to_sql(name='raw_statcan', con=engine, if_exists='append', index=True)

IntegrityError: (psycopg2.errors.UniqueViolation) duplicate key value violates unique constraint "raw_statcan_pkey"
DETAIL:  Key (index)=(0) already exists.

[SQL: INSERT INTO raw_statcan (index, ethnicity, topic, characteristics, "AB", "BC", "MB", "SK", "NL", "NS", "NB", "NU", "PE", "QC", "ON", "YU", "NW", "National", "AB_Male", "BC_Male", "MB_Male", "SK_Male", "NL_Male", "NS_Male", "NB_Male", "PE_Male", "NU_Male", "QC_Male", "ON_Male", "YU_Male", "NW_Male", "National_Male", "AB_Female", "BC_Female", "MB_Female", "SK_Female", "NL_Female", "NS_Female", "NB_Female", "PE_Female", "NU_Female", "QC_Female", "ON_Female", "YU_Female", "NW_Female", "National_Female") VALUES (%(index)s, %(ethnicity)s, %(topic)s, %(characteristics)s, %(AB)s, %(BC)s, %(MB)s, %(SK)s, %(NL)s, %(NS)s, %(NB)s, %(NU)s, %(PE)s, %(QC)s, %(ON)s, %(YU)s, %(NW)s, %(National)s, %(AB_Male)s, %(BC_Male)s, %(MB_Male)s, %(SK_Male)s, %(NL_Male)s, %(NS_Male)s, %(NB_Male)s, %(PE_Male)s, %(NU_Male)s, %(QC_Male)s, %(ON_Male)s, %(YU_Male)s, %(NW_Male)s, %(National_Male)s, %(AB_Female)s, %(BC_Female)s, %(MB_Female)s, %(SK_Female)s, %(NL_Female)s, %(NS_Female)s, %(NB_Female)s, %(PE_Female)s, %(NU_Female)s, %(QC_Female)s, %(ON_Female)s, %(YU_Female)s, %(NW_Female)s, %(National_Female)s)]
[parameters: ({'index': 0, 'ethnicity': 'Aboriginal', 'topic': 'Ethnic origin population', 'characteristics': '  North American Aboriginal origins', 'AB': 303815, 'BC': 302810, 'MB': 225230, 'SK': 177355, 'NL': 58550, 'NS': 74040, 'NB': 46585, 'NU': 30420, 'PE': 4960, 'QC': 359430, 'ON': 518300, 'YU': 8320, 'NW': 20720, 'National': 2130520, 'AB_Male': 147735, 'BC_Male': 146530, 'MB_Male': 109465, 'SK_Male': 85790, 'NL_Male': 28165, 'NS_Male': 34920, 'NB_Male': 22625, 'PE_Male': 2325, 'NU_Male': 15340, 'QC_Male': 172440, 'ON_Male': 247160, 'YU_Male': 4000, 'NW_Male': 10185, 'National_Male': 1026675, 'AB_Female': 156075, 'BC_Female': 156280, 'MB_Female': 115770, 'SK_Female': 91565, 'NL_Female': 30385, 'NS_Female': 39115, 'NB_Female': 23955, 'PE_Female': 2640, 'NU_Female': 15075, 'QC_Female': 186985, 'ON_Female': 271135, 'YU_Female': 4325, 'NW_Female': 10530, 'National_Female': 1103840}, {'index': 1, 'ethnicity': 'White', 'topic': 'Ethnic origin population', 'characteristics': '  Other North American origins', 'AB': 955040, 'BC': 922690, 'MB': 247670, 'SK': 230620, 'NL': 280640, 'NS': 410825, 'NB': 428865, 'NU': 1815, 'PE': 62075, 'QC': 4850145, 'ON': 3220595, 'YU': 9335, 'NW': 8220, 'National': 11628535, 'AB_Male': 486735, 'BC_Male': 460355, 'MB_Male': 123075, 'SK_Male': 115250, 'NL_Male': 137030, 'NS_Male': 197970, 'NB_Male': 209615, 'PE_Male': 29940, 'NU_Male': 960, 'QC_Male': 2390545, 'ON_Male': 1585255, 'YU_Male': 4775, 'NW_Male': 4195, 'National_Male': 5745695, 'AB_Female': 468305, 'BC_Female': 462335, 'MB_Female': 124600, 'SK_Female': 115370, 'NL_Female': 143610, 'NS_Female': 212855, 'NB_Female': 219250, 'PE_Female': 32130, 'NU_Female': 860, 'QC_Female': 2459605, 'ON_Female': 1635340, 'YU_Female': 4565, 'NW_Female': 4020, 'National_Female': 5882835}, {'index': 2, 'ethnicity': 'White', 'topic': 'Ethnic origin population', 'characteristics': '  European origins', 'AB': 2580720, 'BC': 2857080, 'MB': 826210, 'SK': 759080, 'NL': 274460, 'NS': 621525, 'NB': 424850, 'NU': 8315, 'PE': 98615, 'QC': 3037890, 'ON': 8151470, 'YU': 24990, 'NW': 18115, 'National': 19683320, 'AB_Male': 1292280, 'BC_Male': 1408510, 'MB_Male': 406770, 'SK_Male': 375755, 'NL_Male': 134070, 'NS_Male': 299755, 'NB_Male': 206715, 'PE_Male': 47695, 'NU_Male': 4345, 'QC_Male': 1511060, 'ON_Male': 3978900, 'YU_Male': 12525, 'NW_Male': 9335, 'National_Male': 9687715, 'AB_Female': 1288440, 'BC_Female': 1448575, 'MB_Female': 419445, 'SK_Female': 383325, 'NL_Female': 140390, 'NS_Female': 321760, 'NB_Female': 218135, 'PE_Female': 50920, 'NU_Female': 3975, 'QC_Female': 1526825, 'ON_Female': 4172570, 'YU_Female': 12465, 'NW_Female': 8780, 'National_Female': 9995605}, {'index': 3, 'ethnicity': 'Black', 'topic': 'Ethnic origin population', 'characteristics': '  Caribbean origins', 'AB': 36120, 'BC': 25010, 'MB': 10805, 'SK': 3810, 'NL': 885, 'NS': 5220, 'NB': 2275, 'NU': 95, 'PE': 325, 'QC': 201625, 'ON': 462600, 'YU': 165, 'NW': 215, 'National': 749155, 'AB_Male': 18050, 'BC_Male': 12350, 'MB_Male': 5355, 'SK_Male': 2005, 'NL_Male': 455, 'NS_Male': 2580, 'NB_Male': 1045, 'PE_Male': 145, 'NU_Male': 50, 'QC_Male': 93935, 'ON_Male': 213660, 'YU_Male': 70, 'NW_Male': 105, 'National_Male': 349810, 'AB_Female': 18070, 'BC_Female': 12660, 'MB_Female': 5450, 'SK_Female': 1805, 'NL_Female': 430, 'NS_Female': 2640, 'NB_Female': 1230, 'PE_Female': 180, 'NU_Female': 45, 'QC_Female': 107690, 'ON_Female': 248940, 'YU_Female': 95, 'NW_Female': 110, 'National_Female': 399345}, {'index': 4, 'ethnicity': 'Other Minority', 'topic': 'Ethnic origin population', 'characteristics': '  Latin; Central and South American origins', 'AB': 78405, 'BC': 69920, 'MB': 23115, 'SK': 6695, 'NL': 925, 'NS': 3055, 'NB': 2135, 'NU': 65, 'PE': 420, 'QC': 167275, 'ON': 322210, 'YU': 215, 'NW': 205, 'National': 674640, 'AB_Male': 39030, 'BC_Male': 33580, 'MB_Male': 11555, 'SK_Male': 3295, 'NL_Male': 410, 'NS_Male': 1525, 'NB_Male': 1110, 'PE_Male': 215, 'NU_Male': 30, 'QC_Male': 81215, 'ON_Male': 153045, 'YU_Male': 110, 'NW_Male': 90, 'National_Male': 325210, 'AB_Female': 39375, 'BC_Female': 36335, 'MB_Female': 11565, 'SK_Female': 3400, 'NL_Female': 520, 'NS_Female': 1525, 'NB_Female': 1025, 'PE_Female': 205, 'NU_Female': 35, 'QC_Female': 86065, 'ON_Female': 169165, 'YU_Female': 105, 'NW_Female': 110, 'National_Female': 349430}, {'index': 5, 'ethnicity': 'Black', 'topic': 'Ethnic origin population', 'characteristics': '  African origins', 'AB': 136510, 'BC': 59985, 'MB': 28860, 'SK': 16170, 'NL': 2705, 'NS': 17655, 'NB': 6705, 'NU': 465, 'PE': 980, 'QC': 382665, 'ON': 414095, 'YU': 350, 'NW': 780, 'National': 1067930, 'AB_Male': 70620, 'BC_Male': 30635, 'MB_Male': 14980, 'SK_Male': 8480, 'NL_Male': 1470, 'NS_Male': 8560, 'NB_Male': 3535, 'PE_Male': 480, 'NU_Male': 255, 'QC_Male': 196910, 'ON_Male': 203260, 'YU_Male': 165, 'NW_Male': 455, 'National_Male': 539805, 'AB_Female': 65885, 'BC_Female': 29345, 'MB_Female': 13885, 'SK_Female': 7690, 'NL_Female': 1240, 'NS_Female': 9095, 'NB_Female': 3170, 'PE_Female': 495, 'NU_Female': 210, 'QC_Female': 185755, 'ON_Female': 210835, 'YU_Female': 185, 'NW_Female': 330, 'National_Female': 528120}, {'index': 6, 'ethnicity': 'Other Minority', 'topic': 'Ethnic origin population', 'characteristics': '  Asian origins', 'AB': 756335, 'BC': 1312445, 'MB': 178655, 'SK': 99125, 'NL': 10095, 'NS': 42500, 'NB': 19410, 'NU': 615, 'PE': 6485, 'QC': 563150, 'ON': 3100450, 'YU': 2855, 'NW': 3125, 'National': 6095235, 'AB_Male': 370390, 'BC_Male': 624270, 'MB_Male': 88885, 'SK_Male': 49845, 'NL_Male': 5240, 'NS_Male': 21445, 'NB_Male': 9775, 'PE_Male': 3270, 'NU_Male': 280, 'QC_Male': 275170, 'ON_Male': 1506795, 'YU_Male': 1260, 'NW_Male': 1500, 'National_Male': 2958120, 'AB_Female': 385945, 'BC_Female': 688175, 'MB_Female': 89765, 'SK_Female': 49280, 'NL_Female': 4850, 'NS_Female': 21050, 'NB_Female': 9635, 'PE_Female': 3215, 'NU_Female': 335, 'QC_Female': 287980, 'ON_Female': 1593655, 'YU_Female': 1595, 'NW_Female': 1625, 'National_Female': 3137115}, {'index': 7, 'ethnicity': 'Other Minority', 'topic': 'Ethnic origin population', 'characteristics': '  Oceania origins', 'AB': 15500, 'BC': 41125, 'MB': 1525, 'SK': 1430, 'NL': 240, 'NS': 895, 'NB': 470, 'NU': 15, 'PE': 90, 'QC': 3250, 'ON': 20680, 'YU': 170, 'NW': 85, 'National': 85470, 'AB_Male': 7825, 'BC_Male': 20605, 'MB_Male': 740, 'SK_Male': 760, 'NL_Male': 115, 'NS_Male': 450, 'NB_Male': 210, 'PE_Male': 35, 'NU_Male': 0, 'QC_Male': 1730, 'ON_Male': 10435, 'YU_Male': 80, 'NW_Male': 35, 'National_Male': 43030, 'AB_Female': 7680, 'BC_Female': 20520, 'MB_Female': 785, 'SK_Female': 665, 'NL_Female': 125, 'NS_Female': 445, 'NB_Female': 260, 'PE_Female': 55, 'NU_Female': 0, 'QC_Female': 1515, 'ON_Female': 10240, 'YU_Female': 90, 'NW_Female': 50, 'National_Female': 42440})]
(Background on this error at: http://sqlalche.me/e/13/gkpj)

In [6]:
df_rawincarceration = pd.read_csv("../../01Resources/Data/raw_incarceration.csv")

df_rawincarceration.head()

c:\users\user-xx\.conda\envs\pythondata\lib\site-packages\IPython\core\interactiveshell.py:3146: DtypeWarning: Columns (4) have mixed types.Specify dtype option on import or set low_memory=False.
  interactivity=interactivity, compiler=compiler, result=result)

,incustody_community2,province2,ethnicity,year,number,race,race_group,racial_profile,gender,age,incustody_community,supervision_type,sentence_type,aggregate_sentence_length,province,marital_status,religion
0,Community,NS,Black,2012,A1,BLACK,Non Aboriginal,Black,MALE,28,Community,FP,DETERMINATE,1096,NOVA SCOTIA,NaN,BAPTIST
1,Community,PE,White,2012,A2,WHITE,Non Aboriginal,White,MALE,39,Community,FP,DETERMINATE,912,PRINCE EDWARD I,NaN,CATHOLIC - ROMA
2,Community,NB,White,2012,A3,WHITE,Non Aboriginal,White,MALE,35,Community,SR,DETERMINATE,2329,NEW BRUNSWICK,NaN,CATHOLIC - ROMA
3,Community,ON,White,2012,A4,WHITE,Non Aboriginal,White,MALE,41,Community,SR,DETERMINATE,1278,ONTARIO,NaN,NONE
4,Community,BC,White,2012,A5,WHITE,Non Aboriginal,White,MALE,36,Community,SR,DETERMINATE,2192,BRITISH COLUMBI,NaN,OTHER

In [7]:
df_rawincarceration.to_sql(name='raw_incarceration', con=engine, if_exists='append', index=True)

IntegrityError: (psycopg2.errors.UniqueViolation) duplicate key value violates unique constraint "raw_incarceration_pkey"
DETAIL:  Key (index)=(0) already exists.

[SQL: INSERT INTO raw_incarceration (index, incustody_community2, province2, ethnicity, year, number, race, race_group, racial_profile, gender, age, incustody_community, supervision_type, sentence_type, aggregate_sentence_length, province, marital_status, religion) VALUES (%(index)s, %(incustody_community2)s, %(province2)s, %(ethnicity)s, %(year)s, %(number)s, %(race)s, %(race_group)s, %(racial_profile)s, %(gender)s, %(age)s, %(incustody_community)s, %(supervision_type)s, %(sentence_type)s, %(aggregate_sentence_length)s, %(province)s, %(marital_status)s, %(religion)s)]
[parameters: ({'index': 0, 'incustody_community2': 'Community', 'province2': 'NS', 'ethnicity': 'Black', 'year': 2012, 'number': 'A1', 'race': 'BLACK', 'race_group': 'Non Aboriginal', 'racial_profile': 'Black', 'gender': 'MALE', 'age': 28, 'incustody_community': 'Community', 'supervision_type': 'FP', 'sentence_type': 'DETERMINATE', 'aggregate_sentence_length': 1096, 'province': 'NOVA SCOTIA', 'marital_status': None, 'religion': 'BAPTIST'}, {'index': 1, 'incustody_community2': 'Community', 'province2': 'PE', 'ethnicity': 'White', 'year': 2012, 'number': 'A2', 'race': 'WHITE', 'race_group': 'Non Aboriginal', 'racial_profile': 'White', 'gender': 'MALE', 'age': 39, 'incustody_community': 'Community', 'supervision_type': 'FP', 'sentence_type': 'DETERMINATE', 'aggregate_sentence_length': 912, 'province': 'PRINCE EDWARD I', 'marital_status': None, 'religion': 'CATHOLIC - ROMA'}, {'index': 2, 'incustody_community2': 'Community', 'province2': 'NB', 'ethnicity': 'White', 'year': 2012, 'number': 'A3', 'race': 'WHITE', 'race_group': 'Non Aboriginal', 'racial_profile': 'White', 'gender': 'MALE', 'age': 35, 'incustody_community': 'Community', 'supervision_type': 'SR', 'sentence_type': 'DETERMINATE', 'aggregate_sentence_length': 2329, 'province': 'NEW BRUNSWICK', 'marital_status': None, 'religion': 'CATHOLIC - ROMA'}, {'index': 3, 'incustody_community2': 'Community', 'province2': 'ON', 'ethnicity': 'White', 'year': 2012, 'number': 'A4', 'race': 'WHITE', 'race_group': 'Non Aboriginal', 'racial_profile': 'White', 'gender': 'MALE', 'age': 41, 'incustody_community': 'Community', 'supervision_type': 'SR', 'sentence_type': 'DETERMINATE', 'aggregate_sentence_length': 1278, 'province': 'ONTARIO', 'marital_status': None, 'religion': 'NONE'}, {'index': 4, 'incustody_community2': 'Community', 'province2': 'BC', 'ethnicity': 'White', 'year': 2012, 'number': 'A5', 'race': 'WHITE', 'race_group': 'Non Aboriginal', 'racial_profile': 'White', 'gender': 'MALE', 'age': 36, 'incustody_community': 'Community', 'supervision_type': 'SR', 'sentence_type': 'DETERMINATE', 'aggregate_sentence_length': 2192, 'province': 'BRITISH COLUMBI', 'marital_status': None, 'religion': 'OTHER'}, {'index': 5, 'incustody_community2': 'Community', 'province2': 'BC', 'ethnicity': 'White', 'year': 2012, 'number': 'A6', 'race': 'WHITE', 'race_group': 'Non Aboriginal', 'racial_profile': 'White', 'gender': 'FEMALE', 'age': 79, 'incustody_community': 'Community', 'supervision_type': 'FP', 'sentence_type': 'INDETERMINATE', 'aggregate_sentence_length': 0, 'province': 'BRITISH COLUMBI', 'marital_status': None, 'religion': 'JUDAISM'}, {'index': 6, 'incustody_community2': 'Community', 'province2': 'BC', 'ethnicity': 'White', 'year': 2012, 'number': 'A7', 'race': 'WHITE', 'race_group': 'Non Aboriginal', 'racial_profile': 'White', 'gender': 'MALE', 'age': 45, 'incustody_community': 'Community', 'supervision_type': 'FP', 'sentence_type': 'INDETERMINATE', 'aggregate_sentence_length': 0, 'province': 'BRITISH COLUMBI', 'marital_status': None, 'religion': 'CATH NON-SPEC'}, {'index': 7, 'incustody_community2': 'Community', 'province2': 'ON', 'ethnicity': 'White', 'year': 2012, 'number': 'A8', 'race': 'WHITE', 'race_group': 'Non Aboriginal', 'racial_profile': 'White', 'gender': 'MALE', 'age': 33, 'incustody_community': 'Community', 'supervision_type': 'FP', 'sentence_type': 'DETERMINATE', 'aggregate_sentence_length': 913, 'province': 'ONTARIO', 'marital_status': None, 'religion': 'ANGLICAN(EPIS.'}  ... displaying 10 of 160413 total bound parameter sets ...  {'index': 160411, 'incustody_community2': 'Community', 'province2': 'AB', 'ethnicity': 'White', 'year': 2018, 'number': 22769, 'race': 'WHITE', 'race_group': 'Non Indigenous', 'racial_profile': 'White', 'gender': 'MALE', 'age': 35, 'incustody_community': 'Supervised', 'supervision_type': 'FP', 'sentence_type': 'DETERMINATE', 'aggregate_sentence_length': 1277, 'province': 'ALBERTA', 'marital_status': 'DIVORCED', 'religion': 'NONE'}, {'index': 160412, 'incustody_community2': 'Community', 'province2': 'BC', 'ethnicity': 'White', 'year': 2018, 'number': 22770, 'race': 'WHITE', 'race_group': 'Non Indigenous', 'racial_profile': 'White', 'gender': 'FEMALE', 'age': 62, 'incustody_community': 'Supervised', 'supervision_type': 'FP', 'sentence_type': 'DETERMINATE', 'aggregate_sentence_length': 1096, 'province': 'BRITISH COLUMBIA', 'marital_status': 'MARRIED', 'religion': 'ANGLICAN(EPIS.'})]
(Background on this error at: http://sqlalche.me/e/13/gkpj)

In [8]:
df_table1 = pd.read_csv("../../01Resources/Data/table1.csv")

df_table1.head()

,year,PRUID,province,race,sex,province_sex,population,arrested,race_percent_population,race_percent_arrested,race_disparity_index
0,2016,99,National,Black,Female,National-Female,"927,465",72,0.04,0.06,0.417640
1,2016,59,BC,Black,Female,BC-Female,"42,005",0,0.01,0.00,-1.000000
2,2016,48,AB,Black,Female,AB-Female,"83,955",1,0.03,0.00,-0.883769
3,2016,47,SK,Black,Female,SK-Female,"9,495",2,0.01,0.02,0.698360
4,2016,46,MB,Black,Female,MB-Female,"19,335",0,0.02,0.00,-1.000000

In [9]:
df_table1.to_sql(name='table1', con=engine, if_exists='append', index=True)

IntegrityError: (psycopg2.errors.UniqueViolation) duplicate key value violates unique constraint "table1_pkey"
DETAIL:  Key (index)=(0) already exists.

[SQL: INSERT INTO table1 (index, year, "PRUID", province, race, sex, province_sex, population, arrested, race_percent_population, race_percent_arrested, race_disparity_index) VALUES (%(index)s, %(year)s, %(PRUID)s, %(province)s, %(race)s, %(sex)s, %(province_sex)s, %(population)s, %(arrested)s, %(race_percent_population)s, %(race_percent_arrested)s, %(race_disparity_index)s)]
[parameters: ({'index': 0, 'year': 2016, 'PRUID': 99, 'province': 'National', 'race': 'Black', 'sex': 'Female', 'province_sex': 'National-Female', 'population': '927,465', 'arrested': '72', 'race_percent_population': 0.04, 'race_percent_arrested': 0.06, 'race_disparity_index': 0.417639889}, {'index': 1, 'year': 2016, 'PRUID': 59, 'province': 'BC', 'race': 'Black', 'sex': 'Female', 'province_sex': 'BC-Female', 'population': '42,005', 'arrested': '0', 'race_percent_population': 0.01, 'race_percent_arrested': 0.0, 'race_disparity_index': -1.0}, {'index': 2, 'year': 2016, 'PRUID': 48, 'province': 'AB', 'race': 'Black', 'sex': 'Female', 'province_sex': 'AB-Female', 'population': '83,955', 'arrested': '1', 'race_percent_population': 0.03, 'race_percent_arrested': 0.0, 'race_disparity_index': -0.8837694890000001}, {'index': 3, 'year': 2016, 'PRUID': 47, 'province': 'SK', 'race': 'Black', 'sex': 'Female', 'province_sex': 'SK-Female', 'population': '9,495', 'arrested': '2', 'race_percent_population': 0.01, 'race_percent_arrested': 0.02, 'race_disparity_index': 0.69835976}, {'index': 4, 'year': 2016, 'PRUID': 46, 'province': 'MB', 'race': 'Black', 'sex': 'Female', 'province_sex': 'MB-Female', 'population': '19,335', 'arrested': '0', 'race_percent_population': 0.02, 'race_percent_arrested': 0.0, 'race_disparity_index': -1.0}, {'index': 5, 'year': 2016, 'PRUID': 35, 'province': 'ON', 'race': 'Black', 'sex': 'Female', 'province_sex': 'ON-Female', 'population': '459,775', 'arrested': '57', 'race_percent_population': 0.06, 'race_percent_arrested': 0.17, 'race_disparity_index': 2.094457581}, {'index': 6, 'year': 2016, 'PRUID': 24, 'province': 'QC', 'race': 'Black', 'sex': 'Female', 'province_sex': 'QC-Female', 'population': '293,445', 'arrested': '6', 'race_percent_population': 0.06, 'race_percent_arrested': 0.03, 'race_disparity_index': -0.49740199}, {'index': 7, 'year': 2016, 'PRUID': 13, 'province': 'NB', 'race': 'Black', 'sex': 'Female', 'province_sex': 'NB-Female', 'population': '4,400', 'arrested': '0', 'race_percent_population': 0.01, 'race_percent_arrested': 0.0, 'race_disparity_index': -1.0}  ... displaying 10 of 168 total bound parameter sets ...  {'index': 166, 'year': 2016, 'PRUID': 60, 'province': 'YU', 'race': 'Other Minority', 'sex': 'Both', 'province_sex': 'YU', 'population': '3240', 'arrested': '0', 'race_percent_population': 0.07, 'race_percent_arrested': 0.0, 'race_disparity_index': -1.0}, {'index': 167, 'year': 2016, 'PRUID': 62, 'province': 'NU', 'race': 'Other Minority', 'sex': 'Both', 'province_sex': 'NU', 'population': '695', 'arrested': '0', 'race_percent_population': 0.02, 'race_percent_arrested': 0.0, 'race_disparity_index': -1.0})]
(Background on this error at: http://sqlalche.me/e/13/gkpj)

In [10]:
df_table2 = pd.read_csv("../../01Resources/Data/table2.csv")

df_table2.head()

,year,PRUID,province,race,sex,in_custody_community,avg_length,arrested
0,2012,99,National,Black,Female,In Custody,1604,58
1,2012,59,BC,Black,Female,In Custody,0,0
2,2012,48,AB,Black,Female,In Custody,1218,3
3,2012,47,SK,Black,Female,In Custody,0,0
4,2012,46,MB,Black,Female,In Custody,0,0

In [11]:
df_table2.to_sql(name='table2', con=engine, if_exists='append', index=True)

IntegrityError: (psycopg2.errors.UniqueViolation) duplicate key value violates unique constraint "table2_pkey"
DETAIL:  Key (index)=(0) already exists.

[SQL: INSERT INTO table2 (index, year, "PRUID", province, race, sex, in_custody_community, avg_length, arrested) VALUES (%(index)s, %(year)s, %(PRUID)s, %(province)s, %(race)s, %(sex)s, %(in_custody_community)s, %(avg_length)s, %(arrested)s)]
[parameters: ({'index': 0, 'year': 2012, 'PRUID': 99, 'province': 'National', 'race': 'Black', 'sex': 'Female', 'in_custody_community': 'In Custody', 'avg_length': 1604, 'arrested': 58}, {'index': 1, 'year': 2012, 'PRUID': 59, 'province': 'BC', 'race': 'Black', 'sex': 'Female', 'in_custody_community': 'In Custody', 'avg_length': 0, 'arrested': 0}, {'index': 2, 'year': 2012, 'PRUID': 48, 'province': 'AB', 'race': 'Black', 'sex': 'Female', 'in_custody_community': 'In Custody', 'avg_length': 1218, 'arrested': 3}, {'index': 3, 'year': 2012, 'PRUID': 47, 'province': 'SK', 'race': 'Black', 'sex': 'Female', 'in_custody_community': 'In Custody', 'avg_length': 0, 'arrested': 0}, {'index': 4, 'year': 2012, 'PRUID': 46, 'province': 'MB', 'race': 'Black', 'sex': 'Female', 'in_custody_community': 'In Custody', 'avg_length': 0, 'arrested': 0}, {'index': 5, 'year': 2012, 'PRUID': 35, 'province': 'ON', 'race': 'Black', 'sex': 'Female', 'in_custody_community': 'In Custody', 'avg_length': 1724, 'arrested': 47}, {'index': 6, 'year': 2012, 'PRUID': 24, 'province': 'QC', 'race': 'Black', 'sex': 'Female', 'in_custody_community': 'In Custody', 'avg_length': 1104, 'arrested': 5}, {'index': 7, 'year': 2012, 'PRUID': 13, 'province': 'NB', 'race': 'Black', 'sex': 'Female', 'in_custody_community': 'In Custody', 'avg_length': 0, 'arrested': 0}  ... displaying 10 of 1568 total bound parameter sets ...  {'index': 1566, 'year': 2018, 'PRUID': 60, 'province': 'YU', 'race': 'Other Minority', 'sex': 'Male', 'in_custody_community': 'Community', 'avg_length': 0, 'arrested': 0}, {'index': 1567, 'year': 2018, 'PRUID': 62, 'province': 'NU', 'race': 'Other Minority', 'sex': 'Male', 'in_custody_community': 'Community', 'avg_length': 0, 'arrested': 0})]
(Background on this error at: http://sqlalche.me/e/13/gkpj)

In [12]:
df_table3 = pd.read_csv("../../01Resources/Data/table3.csv")

df_table3.head()

,year,PRUID,province,latitude,longitude,aboriginal_disparity_index,black_disparity_index,other_disparity_index,white_disparity_index
0,2016,59,BC,54.0,-125.0,4.017075,1.376684,-0.508596,-0.161238
1,2016,24,QC,54.0,-75.0,1.890492,-0.034500,-0.258146,-0.059577
2,2016,62,NU,62.0,-98.0,0.397107,-1.000000,-1.000000,-1.000000
3,2016,11,PE,46.5,-63.0,-1.000000,-1.000000,-1.000000,0.082519
4,2016,47,SK,54.0,-107.0,3.428393,0.172063,-0.151802,-0.601394

In [13]:
df_table3.to_sql(name='table3', con=engine, if_exists='append', index=True)

ProgrammingError: (psycopg2.errors.UndefinedColumn) column "latitude" of relation "table3" does not exist
LINE 1: ...SERT INTO table3 (index, year, "PRUID", province, latitude, ...
                                                             ^

[SQL: INSERT INTO table3 (index, year, "PRUID", province, latitude, longitude, aboriginal_disparity_index, black_disparity_index, other_disparity_index, white_disparity_index) VALUES (%(index)s, %(year)s, %(PRUID)s, %(province)s, %(latitude)s, %(longitude)s, %(aboriginal_disparity_index)s, %(black_disparity_index)s, %(other_disparity_index)s, %(white_disparity_index)s)]
[parameters: ({'index': 0, 'year': 2016, 'PRUID': 59, 'province': 'BC', 'latitude': 54.0, 'longitude': -125.0, 'aboriginal_disparity_index': 4.017074763, 'black_disparity_index': 1.37668369, 'other_disparity_index': -0.508595651, 'white_disparity_index': -0.16123754}, {'index': 1, 'year': 2016, 'PRUID': 24, 'province': 'QC', 'latitude': 54.0, 'longitude': -75.0, 'aboriginal_disparity_index': 1.8904917319999999, 'black_disparity_index': -0.034499871, 'other_disparity_index': -0.258145752, 'white_disparity_index': -0.059577122999999996}, {'index': 2, 'year': 2016, 'PRUID': 62, 'province': 'NU', 'latitude': 62.0, 'longitude': -98.0, 'aboriginal_disparity_index': 0.397107166, 'black_disparity_index': -1.0, 'other_disparity_index': -1.0, 'white_disparity_index': -1.0}, {'index': 3, 'year': 2016, 'PRUID': 11, 'province': 'PE', 'latitude': 46.5, 'longitude': -63.0, 'aboriginal_disparity_index': -1.0, 'black_disparity_index': -1.0, 'other_disparity_index': -1.0, 'white_disparity_index': 0.08251913599999999}, {'index': 4, 'year': 2016, 'PRUID': 47, 'province': 'SK', 'latitude': 54.0, 'longitude': -107.0, 'aboriginal_disparity_index': 3.4283934339999997, 'black_disparity_index': 0.17206315600000002, 'other_disparity_index': -0.151802042, 'white_disparity_index': -0.60139413}, {'index': 5, 'year': 2016, 'PRUID': 60, 'province': 'YU', 'latitude': 62.0, 'longitude': -135.0, 'aboriginal_disparity_index': 1.39010989, 'black_disparity_index': -1.0, 'other_disparity_index': -1.0, 'white_disparity_index': -0.227551764}, {'index': 6, 'year': 2016, 'PRUID': 46, 'province': 'MB', 'latitude': 54.0, 'longitude': -99.0, 'aboriginal_disparity_index': 2.7471915630000003, 'black_disparity_index': 0.37497251200000004, 'other_disparity_index': -0.376268418, 'white_disparity_index': -0.518800753}, {'index': 7, 'year': 2016, 'PRUID': 35, 'province': 'ON', 'latitude': 54.0, 'longitude': -90.0, 'aboriginal_disparity_index': 2.8178444139999996, 'black_disparity_index': 2.640484745, 'other_disparity_index': -0.460718991, 'white_disparity_index': -0.192487152}  ... displaying 10 of 14 total bound parameter sets ...  {'index': 12, 'year': 2016, 'PRUID': 12, 'province': 'NS', 'latitude': 45.0, 'longitude': -65.0, 'aboriginal_disparity_index': 0.654884868, 'black_disparity_index': 5.018428226, 'other_disparity_index': 0.18554614100000003, 'white_disparity_index': -0.166516046}, {'index': 13, 'year': 2016, 'PRUID': 99, 'province': 'National', 'latitude': None, 'longitude': None, 'aboriginal_disparity_index': 3.334067045, 'black_disparity_index': 1.007772723, 'other_disparity_index': -0.465113459, 'white_disparity_index': -0.18350851399999998})]
(Background on this error at: http://sqlalche.me/e/13/f405)

In [14]:
df_table4 = pd.read_csv("../../01Resources/Data/table4.csv")

df_table4.head()

   year  province   race in_custody_community   avg_length
0  2012  National  Black           In Custody  1584.018024
1  2012        BC  Black           In Custody  1501.666667
2  2012        AB  Black           In Custody  1512.096154
3  2012        SK  Black           In Custody  1272.782609
4  2012        MB  Black           In Custody  1929.000000

In [17]:
df_table4.to_sql(name='table4', con=engine, if_exists='append', index=True)

IntegrityError: (psycopg2.errors.UniqueViolation) duplicate key value violates unique constraint "table4_pkey"
DETAIL:  Key (index)=(0) already exists.

[SQL: INSERT INTO table4 (index, year, province, race, in_custody_community, avg_length) VALUES (%(index)s, %(year)s, %(province)s, %(race)s, %(in_custody_community)s, %(avg_length)s)]
[parameters: ({'index': 0, 'year': 2012, 'province': 'National', 'race': 'Black', 'in_custody_community': 'In Custody', 'avg_length': 1584.018024}, {'index': 1, 'year': 2012, 'province': 'BC', 'race': 'Black', 'in_custody_community': 'In Custody', 'avg_length': 1501.666667}, {'index': 2, 'year': 2012, 'province': 'AB', 'race': 'Black', 'in_custody_community': 'In Custody', 'avg_length': 1512.0961539999998}, {'index': 3, 'year': 2012, 'province': 'SK', 'race': 'Black', 'in_custody_community': 'In Custody', 'avg_length': 1272.782609}, {'index': 4, 'year': 2012, 'province': 'MB', 'race': 'Black', 'in_custody_community': 'In Custody', 'avg_length': 1929.0}, {'index': 5, 'year': 2012, 'province': 'ON', 'race': 'Black', 'in_custody_community': 'In Custody', 'avg_length': 1571.650286}, {'index': 6, 'year': 2012, 'province': 'QC', 'race': 'Black', 'in_custody_community': 'In Custody', 'avg_length': 1719.0354329999998}, {'index': 7, 'year': 2012, 'province': 'NB', 'race': 'Black', 'in_custody_community': 'In Custody', 'avg_length': 1461.976744}  ... displaying 10 of 923 total bound parameter sets ...  {'index': 921, 'year': 2018, 'province': 'NL', 'race': 'Other Minority', 'in_custody_community': 'Both', 'avg_length': 990.4}, {'index': 922, 'year': 2018, 'province': 'NW', 'race': 'Other Minority', 'in_custody_community': 'Both', 'avg_length': 1270.0})]
(Background on this error at: http://sqlalche.me/e/13/gkpj)